### ISSUE TITLE
(Discussion) Remove `pytaglib` dependency

### ISSUE THREAD

**Issue by Rawrior** [SEbbaDK/sonica#35]
It's not currently used, so we should consider moving away from it before it's too late. Some of our contributors can't install it, meaning it would be hard or impossible for them to test their changes.

As an alternative, we could go completely library-free, and keep track of the tags in a separate json file, though this would also incur some development overhead.

**Comment by SEbbaDK** [comment]
It seems to be problematic on both windows x64 and armv7/8 systems, so i think we need to.
But we should find a good alternative since `mediafile` won't work as it doesn't support arbitrary tag names like `pytaglib` (and is also way slower).
We could look at [`eyed3`](https://eyed3.readthedocs.io/en/latest/)
